<?php
/**
 * Nightingale-BuddyBoss  functions and definitions
 *
 * @link      https://developer.wordpress.org/themes/basics/theme-functions/
 * @package   Nightingale
 * @copyright NHS Leadership Academy, Tony Blacker
 * @version   2.2.8 8th December 2020
 */
add_action( 'wp_enqueue_scripts', 'enqueue_child_styles', 20 );

function enqueue_child_styles() {
	wp_dequeue_style( 'nightingale-style' );
	wp_enqueue_style( 'buddyboss-style', get_stylesheet_uri(), '', '20201208' );
}
/**
 * Create an array of active plugins.
 */

$active_plugins  = apply_filters( 'active_plugins', get_option( 'active_plugins' ) );
$network_plugins = apply_filters( 'active_plugins', get_site_option( 'active_sitewide_plugins' ) );
if ( ! empty( $network_plugins ) ) { // add network plugins to array if network array isn't empty.
	foreach ( $network_plugins as $key => $value ) {
		$active_plugins[] = $key;
	}
}

/**
 * BuddyBoss theming.
 * N.B. This is not a plugin, nor does it provide any plugin-like changes. This is a theme file for
 * BuddyBoss plugin so any content generated by BuddyBoss fits in to this theme.
 * The check around the require is to see if the plugin is active on this install
 */
if ( in_array( 'buddyboss-platform/bp-loader.php', $active_plugins, true ) ) {
	if ( ! is_admin() ) {
		require get_theme_file_path( '/inc/buddyboss.php' );
	}
}

/**
 * Function to show/hide buddy icons when search activated on mobile
 * This seems counterintuitive, because it fires *before* the class "is-active" gets modified.
 */
function nightingale_buddy_search_mobile_fix() {
	echo "<script>

jQuery('#toggle-search').click(function() {
  	if (jQuery(this).is('.is-active')) {
	    jQuery('.buddypress-header').show();
	} else {
	  console.log('that happened');  
	    jQuery('.buddypress-header').hide();
	}
});
jQuery('#close-search').click(function() {
  jQuery('.buddypress-header').show();
});
</script>";
}
add_action( 'wp_footer', 'nightingale_buddy_search_mobile_fix' );

